// =============================================================================
// ARTSY PRODUCTION — META WHATSAPP CLOUD API HSM TEMPLATES CATALOG (44 EVENTS)
// =============================================================================

export interface WhatsappTemplateDef {
  eventNumber: number;
  templateName: string;
  category: 'AUTHENTICATION' | 'UTILITY' | 'MARKETING';
  language: string;
  parameterKeys: string[];
  sampleText: string;
}

export const WHATSAPP_TEMPLATES: Record<number, WhatsappTemplateDef> = {
  1: {
    eventNumber: 1,
    templateName: 'artsy_otp_verification',
    category: 'AUTHENTICATION',
    language: 'en',
    parameterKeys: ['otp'],
    sampleText: 'Your Artsy verification code is {{1}}. Valid for 5 minutes. Do not share this code.',
  },
  2: {
    eventNumber: 2,
    templateName: 'artsy_creator_application_received',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['alias'],
    sampleText: 'Hi {{1}}, your creator application has been submitted to Studio Curation. We will review your portfolio within 24-48 hours.',
  },
  3: {
    eventNumber: 3,
    templateName: 'artsy_creator_approved',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['alias'],
    sampleText: 'Welcome to Artsy Production, {{1}}! Your editor profile is approved. You are now eligible to receive project offers.',
  },
  4: {
    eventNumber: 4,
    templateName: 'artsy_creator_rejected',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['alias'],
    sampleText: 'Thank you for your interest, {{1}}. At this time, our roster does not match your reel. You may reapply in 60 days.',
  },
  5: {
    eventNumber: 5,
    templateName: 'artsy_quote_ready',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['serviceName', 'amount'],
    sampleText: 'Your custom quote for {{1}} (₹{{2}}) is ready. View breakdown and lock checkout within 7 days.',
  },
  6: {
    eventNumber: 6,
    templateName: 'artsy_payment_confirmed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['amount', 'orderId'],
    sampleText: 'Payment of ₹{{1}} confirmed for Order #{{2}}. Upload your raw footage to initiate timeline assembly.',
  },
  7: {
    eventNumber: 7,
    templateName: 'artsy_payment_failed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['orderId'],
    sampleText: 'Payment transaction failed for Order #{{1}}. Tap to retry checkout.',
  },
  8: {
    eventNumber: 8,
    templateName: 'artsy_upload_reminder',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['orderId'],
    sampleText: 'Friendly reminder: Please upload your project footage for Order #{{1}} so our editing team can begin.',
  },
  9: {
    eventNumber: 9,
    templateName: 'artsy_upload_complete',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Your raw footage for Project #{{1}} has been safely ingested and verified. Assigned to editorial queue.',
  },
  10: {
    eventNumber: 10,
    templateName: 'artsy_upload_integrity_failed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'One or more clips for Project #{{1}} failed integrity check. Please re-upload your missing clips.',
  },
  11: {
    eventNumber: 11,
    templateName: 'artsy_creator_assigned',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId', 'creatorName'],
    sampleText: 'Lead editor {{2}} has been assigned to Project #{{1}}.',
  },
  12: {
    eventNumber: 12,
    templateName: 'artsy_job_offered',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['serviceName', 'payout'],
    sampleText: 'New project offer: {{1}} (Net Payout: ₹{{2}}). Respond within 24 hours to secure assignment.',
  },
  13: {
    eventNumber: 13,
    templateName: 'artsy_job_accepted',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Creator accepted Project #{{1}}. Ingest credentials issued.',
  },
  14: {
    eventNumber: 14,
    templateName: 'artsy_job_declined',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Creator declined Project #{{1}}. Reassigning to reserve editor.',
  },
  15: {
    eventNumber: 15,
    templateName: 'artsy_acceptance_timeout',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: '24-hour acceptance window expired for Project #{{1}}. Job returned to curation queue.',
  },
  16: {
    eventNumber: 16,
    templateName: 'artsy_daily_checkin',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Please submit your daily editing milestone for Project #{{1}}.',
  },
  17: {
    eventNumber: 17,
    templateName: 'artsy_checkin_missed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Check-in missed for Project #{{1}}. Admin attention required.',
  },
  18: {
    eventNumber: 18,
    templateName: 'artsy_deadline_risk',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Project #{{1}} internal deadline approaching in less than 24 hours.',
  },
  19: {
    eventNumber: 19,
    templateName: 'artsy_deliverable_submitted',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'New timeline export submitted for Project #{{1}}. Ready for Studio QA review.',
  },
  20: {
    eventNumber: 20,
    templateName: 'artsy_qa_passed_preview_ready',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Studio QA complete! Your private preview link for Project #{{1}} is ready. Review and leave frame comments.',
  },
  21: {
    eventNumber: 21,
    templateName: 'artsy_qa_failed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'QA review requires adjustments on audio/color consistency for Project #{{1}} before client preview.',
  },
  22: {
    eventNumber: 22,
    templateName: 'artsy_revision_requested',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Client has submitted revision comments on Project #{{1}}. Please review notes.',
  },
  23: {
    eventNumber: 23,
    templateName: 'artsy_review_reminder',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Your preview cut for Project #{{1}} is ready. Auto-approval activates in 48 hours.',
  },
  24: {
    eventNumber: 24,
    templateName: 'artsy_auto_approved',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: '7-day client review period elapsed. Project #{{1}} has been auto-approved for master export.',
  },
  25: {
    eventNumber: 25,
    templateName: 'artsy_project_completed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Your master 4K / HD delivery package for Project #{{1}} is ready for download.',
  },
  26: {
    eventNumber: 26,
    templateName: 'artsy_change_order_created',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId', 'amount'],
    sampleText: 'Scope update required for Project #{{1}}: ₹{{2}} for additional deliverables.',
  },
  27: {
    eventNumber: 27,
    templateName: 'artsy_change_order_accepted',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Change order approved and funded for Project #{{1}}. Extra scope unlocked.',
  },
  28: {
    eventNumber: 28,
    templateName: 'artsy_change_order_declined',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Client declined scope change on Project #{{1}}. Proceeding with original delivery specification.',
  },
  29: {
    eventNumber: 29,
    templateName: 'artsy_payout_scheduled',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['amount', 'projectId'],
    sampleText: 'Project #{{2}} approved! Net payout of ₹{{1}} scheduled for NEFT release within 7 days.',
  },
  30: {
    eventNumber: 30,
    templateName: 'artsy_payout_processed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['amount', 'utr', 'tds'],
    sampleText: 'NEFT Payout of ₹{{1}} successfully processed (UTR: {{2}}). Section 194J TDS withheld: ₹{{3}}.',
  },
  31: {
    eventNumber: 31,
    templateName: 'artsy_payout_failed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['amount'],
    sampleText: 'NEFT transfer of ₹{{1}} failed due to invalid IFSC / account number. Please verify bank credentials.',
  },
  32: {
    eventNumber: 32,
    templateName: 'artsy_refund_initiated',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['amount'],
    sampleText: 'Refund of ₹{{1}} initiated. Amount will reflect in original payment method in 5-7 business days.',
  },
  33: {
    eventNumber: 33,
    templateName: 'artsy_refund_processed',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['amount'],
    sampleText: 'Refund of ₹{{1}} settled. Statutory GST credit note generated.',
  },
  34: {
    eventNumber: 34,
    templateName: 'artsy_dispute_opened',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Dispute opened for Project #{{1}}. Studio Admin has initiated manual review.',
  },
  35: {
    eventNumber: 35,
    templateName: 'artsy_raw_retention_7d',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Raw footage for Project #{{1}} will be deleted in 7 days. Extend retention in dashboard.',
  },
  36: {
    eventNumber: 36,
    templateName: 'artsy_raw_retention_3d',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'URGENT: Raw footage for Project #{{1}} will be permanently archived in 3 days.',
  },
  37: {
    eventNumber: 37,
    templateName: 'artsy_raw_retention_1d',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'FINAL NOTICE: Raw footage for Project #{{1}} will be purged tomorrow.',
  },
  38: {
    eventNumber: 38,
    templateName: 'artsy_raw_retention_purged',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Raw footage for Project #{{1}} soft deleted according to 15-day retention policy.',
  },
  39: {
    eventNumber: 39,
    templateName: 'artsy_final_retention_7d',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Master export link for Project #{{1}} expires in 7 days. Download your final films.',
  },
  40: {
    eventNumber: 40,
    templateName: 'artsy_final_retention_3d',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Master video files for Project #{{1}} will be archived in 3 days.',
  },
  41: {
    eventNumber: 41,
    templateName: 'artsy_final_retention_purged',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Final video files for Project #{{1}} archived from hot CDN storage.',
  },
  42: {
    eventNumber: 42,
    templateName: 'artsy_creator_suspended',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['alias'],
    sampleText: 'Notice: Your editor account has been temporarily paused by Studio Administration.',
  },
  43: {
    eventNumber: 43,
    templateName: 'artsy_project_cancelled',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Project #{{1}} cancelled. Cancellation terms applied per platform policy.',
  },
  44: {
    eventNumber: 44,
    templateName: 'artsy_sla_breach_concession',
    category: 'UTILITY',
    language: 'en',
    parameterKeys: ['projectId'],
    sampleText: 'Turnaround deadline exceeded on Project #{{1}}. 10% credit applied to account.',
  },
};
